version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - mssql-server
    mssql-server:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            -SA_PASSWORD: "Harveymark2019$"
            -ACCEPT_EULA: "Y"
